---
plex_dir: "{{ services_dir }}/plex"
plex_owner: "{{ services_owner }}"
plex_group: "{{ services_group }}"
plex_dir_mode: "{{ services_dir_mode }}"
plex_file_mode: "{{ services_file_mode }}"

plex_version: latest
plex_container_name: plex
plex_watchtower_enabled: "{{ services_watchtower_enabled }}"
plex_timezone: "{{ services_timezone }}"
plex_client_identifier: "X-Plex-Client-Identifier"
plex_username: "admin@localhost"
plex_password: "admin"
plex_deploy_resources_limits:
  cpus: "2.0"
  memory: 4G
plex_volumes: []
plex_networks: []
plex_bind_ip: "{{ services_bind_ip }}"
plex_ports:
  - "{{ plex_server_port }}:{{ plex_server_port }}/tcp"
  - 1900:1900/udp
  - 32469:32469/tcp
  - 8324:8324/tcp
  - 32410:32410/udp
  - 32412:32412/udp
  - 32413:32413/udp
  - 32414:32414/udp

plex_nginx_server_name: "{{ plex_container_name }}.{{ domain }}"
