---
- name: Nginx Role - Nginx service deployment
  ansible.builtin.debug:
    msg:
      - "=============================="
      - "  Nginx: service deployment"
      - "=============================="

- name: Include Nginx tasks
  ansible.builtin.include_tasks: nginx.yml
