scrape_configs:
  - job_name: nut-primary
    metrics_path: /ups_metrics
    static_configs:
      - targets: ['{{ nut_ui_exporter_container_name | default("nut-exporter") }}:9199']
        labels:
          ups: "{{ nut_ups_name }}"
    params:
      ups: [ "{{ nut_ups_name }}" ]
