---
# Global
domain: "example.com"

# Bootstrap
services_dir: /opt
services_owner: "{{ ansible_user_id }}"
services_group: root
services_dir_mode: "0770"
services_file_mode: "0660"

# Certbot
certbot_domain: "stub.com"
certbot_cf_email: "test@example.com"
certbot_cf_api_token: "1234567890abcdef1234567890abcdef1234"
certbot_dir: "{{ services_dir }}/certbot"

# Nginx
nginx_ssl_keys_server_path: "/etc/ssl/private/{{ domain }}.key"
nginx_ssl_certs_server_path: "/etc/ssl/certs/{{ domain }}.crt"
nginx_dir: "{{ services_dir }}/nginx"
nginx_conf_files:
  - "{{ molecule_scenario_directory }}/nginx/templates/htpasswd.conf"
nginx_user: testadmin
nginx_password: testadminpassword
