---
# Global
domain: "example.com"

# System
system_update_only: true

# Bootstrap
services_dir: /opt/services
services_owner: "{{ ansible_user_id }}"
services_group: root
services_dir_mode: "0770"
services_file_mode: "0660"

# Certbot
certbot_domain: "stub.com"
certbot_cf_email: "test@example.com"
certbot_cf_api_token: "1234567890abcdef1234567890abcdef1234"
certbot_dir: "{{ services_dir }}/certbot"

# Nginx
nginx_ssl_keys_server_path: "/etc/ssl/private/{{ domain }}.key"
nginx_ssl_certs_server_path: "/etc/ssl/certs/{{ domain }}.crt"
nginx_dir: "{{ services_dir }}/nginx"
nginx_conf_files:
  - "{{ molecule_scenario_directory }}/roles/nginx/templates/htpasswd.conf"
nginx_user: testadmin
nginx_password: testadminpassword

# Watchtower
watchtower_dir: "{{ services_dir }}/watchtower"

# NUT UI
nut_ui_dir: "{{ services_dir }}/nut-ui"
nut_ups_name: eaton
nut_upsd_listen_port: 3493
nut_users_admin_name: nutuser
nut_users_admin_password: nutpassword
nut_users_monitor_name: nutuser
nut_users_monitor_password: nutpassword

# Monitor
monitor_dir: "{{ services_dir }}/monitor"
monitor_grafana_container_name: monitor-grafana
monitor_prometheus_container_name: monitor-prometheus
monitor_cadvisor_container_name: monitor-cadvisor
monitor_node_exporter_container_name: monitor-node-exporter
monitor_conf_roles:
  - scalified.services.nut_ui
