---
watchtower_dir: "{{ services_dir }}/watchtower"
watchtower_owner: "{{ services_owner }}"
watchtower_group: "{{ services_group }}"
watchtower_dir_mode: "{{ services_dir_mode }}"
watchtower_file_mode: "{{ services_file_mode }}"

watchtower_version: latest
watchtower_container_name: watchtower
watchtower_deploy_resources_limits:
  cpus: "0.50"
  memory: 500M

watchtower_timezone: "{{ services_timezone }}"
watchtower_cleanup: true
watchtower_remove_volumes: true
watchtower_include_restarting: false
watchtower_include_stopped: false
watchtower_revive_stopped: false
watchtower_label_enable: true
watchtower_disable_containers: ""
watchtower_monitor_only: false
watchtower_label_take_precedence: false
watchtower_no_restart: false
watchtower_no_pull: false
watchtower_no_startup_message: true
watchtower_scope: ""
watchtower_schedule: "0 23 3 * * *"
watchtower_rolling_restart: true
watchtower_timeout: 10s
watchtower_notifications_hostname: "{{ ansible_host }}"
watchtower_notification_url: ""
