---
- name: Certbot Role - SSL certificate management
  ansible.builtin.debug:
    msg:
      - "======================================="
      - "  Certbot: SSL certificate management"
      - "======================================="

- name: Include Certbot tasks
  ansible.builtin.include_tasks: certbot.yml
