---
galaxy_info:
  author: Vladyslav Baidak <vld.x@hotmail.com>
  description: Plex Media Server - a service for media organization and streaming
  company: Scalified
  license: MIT
  min_ansible_version: "2.16"

  galaxy_tags:
    - plex

dependencies:
  - role: scalified.services.bootstrap
