---
galaxy_info:
  author: Vladyslav Baidak <vld.x@hotmail.com>
  description: Watchtower service for automating Docker container base image updates
  company: Scalified
  license: MIT
  min_ansible_version: "2.16"

  galaxy_tags:
    - watchtower
    - docker

dependencies:
  - role: scalified.services.bootstrap
