---
galaxy_info:
  author: Vladyslav Baidak <vld.x@hotmail.com>
  description: Monitor service including Prometheus, Grafana, cAdvisor, and Node Exporter
  company: Scalified
  license: MIT
  min_ansible_version: "2.16"

  galaxy_tags:
    - monitoring
    - grafana
    - prometheus
    - cadvisor
    - node-exporter

dependencies:
  - role: scalified.services.bootstrap
